"""init

Revision ID: 75d571e29746
Revises: 
Create Date: 2026-05-03 20:39:58.607615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d571e29746'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('comparison_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('algorithms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithms_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_history_created_at'), 'comparison_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_comparison_history_user_id'), 'comparison_history', ['user_id'], unique=False)
    op.create_table('solve_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solve_history_created_at'), 'solve_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_solve_history_user_id'), 'solve_history', ['user_id'], unique=False)
    op.drop_index('ix_comparison_results_id', table_name='comparison_results')
    op.drop_index('ix_comparison_results_problem_type', table_name='comparison_results')
    op.drop_table('comparison_results')
    op.drop_index('ix_results_algorithm', table_name='results')
    op.drop_index('ix_results_id', table_name='results')
    op.drop_index('ix_results_problem_type', table_name='results')
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('convergence_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.create_index('ix_results_problem_type', 'results', ['problem_type'], unique=False)
    op.create_index('ix_results_id', 'results', ['id'], unique=False)
    op.create_index('ix_results_algorithm', 'results', ['algorithm'], unique=False)
    op.create_table('comparison_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='comparison_results_pkey')
    )
    op.create_index('ix_comparison_results_problem_type', 'comparison_results', ['problem_type'], unique=False)
    op.create_index('ix_comparison_results_id', 'comparison_results', ['id'], unique=False)
    op.drop_index(op.f('ix_solve_history_user_id'), table_name='solve_history')
    op.drop_index(op.f('ix_solve_history_created_at'), table_name='solve_history')
    op.drop_table('solve_history')
    op.drop_index(op.f('ix_comparison_history_user_id'), table_name='comparison_history')
    op.drop_index(op.f('ix_comparison_history_created_at'), table_name='comparison_history')
    op.drop_table('comparison_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
